name: counter_app
description: A Flutter application that implements a counter which multiplies the counter value by 10 using the Cubit pattern for state management.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.0
  mocktail: ^0.1.0

flutter:
  uses-material-design: true